#include "iostream.h";
#include <conio.h>;
#include "ctype.h";
void main(){
/*	clrscr();
	int i;int sum;int x[100];	char* t;
	char string[1000];
	for (i=0; i<100; i++)
		sum += x[i];
	cout <<sum<<"\nNapisi Nesto (Ama Bez Prazni Mesta)\n";
	cin >>string;
	clrscr();
	for (i=0, t=string; i < 40 && *t; i++, t++){
		putch(*t);
		putch('\n');
//    cout << "\n";
	}*/
	clrscr();
	char a;
	for (/*cout <<" Pritisni kopce "*/;; ) {
		//if(isascii(a)){ break;};
		cout <<" Pritisni kopce ";
    getch();
		}
}